### ISSUE TITLE
mixpanel_flutter-2.3.3 cannot find symbol import io.flutter.plugin.common.PluginRegistry.Registrar

### ISSUE THREAD

**Issue by stefanmusat** [mixpanel/mixpanel-flutter#177]
After upgrading flutter to 3.29.0 stable the latest version of mixpanel throws this:

mixpanel_flutter-2.3.3/android/src/main/java/com/mixpanel/mixpanel_flutter/MixpanelFlutterPlugin.java:22: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry

**Comment by Inakitajes** [comment]
Is anyone at the wheel here, or is this a complete mess? It’s embarrassing that a company like Mixpanel, with a service that literally costs hundreds or thousands of dollars a month, hasn’t updated a dependency that’s been deprecated for 4 years now. 

This is breaking builds in production. In our case, we’re stuck—we can’t roll back to Flutter 3.27 because of a bug that breaks our app, but we also can’t update to 3.29 because Mixpanel won’t compile. What are we supposed to do? Switch to Amplitude?

**Comment by yelkamel** [comment]
Need it

**Comment by nikb7** [comment]
You can use this for a temp fix - https://github.com/mixpanel/mixpanel-flutter/pull/172
```
  mixpanel_flutter:
    git:
      url: git@github.com:nikb7/mixpanel-flutter.git
      ref: v1-embedding
```

**Comment by Inakitajes** [comment]
Thank you, @nikb7 

I find it really difficult to understand how a PR of literally a line of code, related to an unused import, can be pending to be merged for two months...

Could someone from the Mixpanel team provide an explanation?

**Comment by cgs** [comment]
Not confidence inspiring. As my app is unreleased I might just try Amplitude now.

**Comment by GiantChipmunk** [comment]
too

**Comment by yelkamel** [comment]
@john-mixpanel @mixpanel-rhoeun @rahul-mixpanel @leondai-mixpanel 

Can someone fix that and make an update please ?

I can't say yes to that: 

![Image](https://github.com/user-attachments/assets/35abec4c-5b22-464e-8f16-5af854eb76f8)

**Comment by nosadaniel** [comment]
try this way

mixpanel_flutter:
    git:
      url: https://github.com/nikb7/mixpanel-flutter.git
      ref: v1-embedding

**Comment by jaredmixpanel** [comment]
Apologies this went unaddressed for so long. `v2.3.4` has just been released which removes the `PluginRegistry.Registrar` dependency.
